<!DOCTYPE html>
<html>
<head>
    <title>Sales Return Report - Print</title>
    <style>
        body { font-family: Arial, sans-serif; font-size: 12px; }
        .header { text-align: center; margin-bottom: 20px; }
        .info { margin-bottom: 15px; text-align: center; }
        table { width: 100%; border-collapse: collapse; margin-top: 10px; }
        th, td { border: 1px solid #ccc; padding: 5px; text-align: left; }
        th { background-color: #f2f2f2; }
        .text-right { text-align: right; }
        .text-center { text-align: center; }
        @media print {
            .no-print { display: none; }
        }
    </style>
</head>
<body onload="window.print()">
    <div class="header">
        <h2>Hospital Management System</h2>
        <h3>Sales Return Report</h3>
    </div>
    
    <div class="info">
        <p>From: <strong><?php echo date('M d, Y', strtotime($cFrom));?></strong> To: <strong><?php echo date('M d, Y', strtotime($cTo));?></strong></p>
    </div>
    
    <table>
        <thead>
            <tr>
                <th>Return No</th>
                <th>Date</th>
                <th>Patient</th>
                <th>Item Name</th>
                <th>Qty</th>
                <th>Price</th>
                <th>Total Refund</th>
                <th>Remarks</th>
            </tr>
        </thead>
        <tbody>
            <?php 
            $grand_total = 0;
            if(!empty($returns)):
                foreach($returns as $ret){
                    $details = $this->pharmacy_reports_model->getReturnDetails($ret->return_id);
                    foreach($details as $item){
                        $total = $item->qty * $item->price;
                        $grand_total += $total;
            ?>
            <tr>
                <td><?php echo $ret->return_no;?></td>
                <td><?php echo date('M d, Y h:i A', strtotime($ret->date_return));?></td>
                <td><?php echo $ret->patient_name ? $ret->patient_name : 'Walk-in / Unknown';?></td>
                <td><?php echo $item->drug_name;?></td>
                <td class="text-center"><?php echo $item->qty;?></td>
                <td class="text-right"><?php echo number_format($item->price, 2);?></td>
                <td class="text-right"><?php echo number_format($total, 2);?></td>
                <td><?php echo $ret->remarks;?></td>
            </tr>
            <?php 
                    }
                }
            else:
            ?>
            <tr><td colspan="8" class="text-center">No returns found.</td></tr>
            <?php endif;?>
        </tbody>
        <tfoot>
            <tr style="font-weight:bold; font-size:14px;">
                <td colspan="6" class="text-right">Total Returns:</td>
                <td class="text-right"><?php echo number_format($grand_total, 2);?></td>
                <td></td>
            </tr>
        </tfoot>
    </table>
    
    <div style="margin-top: 30px;">
        <p>Generated By: <?php echo $this->session->userdata('firstname') . ' ' . $this->session->userdata('lastname'); ?> | Date: <?php echo date('Y-m-d H:i:s'); ?></p>
    </div>
</body>
</html>